name: CI/CD Pipeline

on:
  # Trigger the workflow on any push to the main branch
  push:
    branches:
      - main
  

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t mooaz/my-node-app:${{ github.run_number }} .
          docker push mooaz/my-node-app:${{ github.run_number }}
      - name: Add Host to Known Hosts
        run:  ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts


      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Kind Cluster
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          export KUBECONFIG=$HOME/.kube/config
          kubectl set image deployment/nodejs-app nodejs-app=mooaz/my-node-app:${{ github.run_number }}
          kubectl rollout status deployment/nodejs-app
          EOF
